### PR TITLE
updated introspection_endpoint logic

### PR DESCRIPTION
**Pull request by kgbsmurf**
My first pull request ever, not sure what I am doing.  Please guide me if I am missing something.
These changes fixed my app in Keycloak 11.

### CODE REVIEW

**Comment by kgbsmurf** [comment]
this is related to #31

**Comment by MoatazAbdallh** [comment]
Why maintainers are not merging this PR because this gem now not working with the latest keycloak

**Comment by DarianAnjuhal** [comment]
I guess this project is not maintained anymore. I will fork it and add the necessary fixes.

Does anyone have access to this project in order the change couple of things?

**Comment by lvitals** [comment]
The reported issue was fixed in PR #43

**Pull request closed without merging**
