### PR TITLE
Change installation file format from json to yaml

### PR DESCRIPTION
**Pull request by shiralwz**
After we changed the installation file format from .json to .yml, we could use environmental variables in the installation file
For example: 
`realm: <%= ENV['KEYCLOAK_REALM'] %>`

It will be easy for us to configure the settings by different environments.

And upgrade the version of bundler version from '1.15' to '2.0.2'

I tested it in my local, it works.

### CODE REVIEW

**Comment by shiralwz** [comment]
@g-portugues would you mind review this PR, thanks

**Comment by g-portugues** [comment]
> @g-portugues would you mind review this PR, thanks

Hi, @shiralwz !
Thank you for your PR.
The reason for working with the json file is that Keycloak provides the client installation file in json format.
An alternative is to use `config/initializers/keycloak.rb` to set realm and auth_server_url using environment variables.

https://github.com/imagov/keycloak#module-keycloak

**Comment by shiralwz** [comment]
@g-portugues  Thanks for your reply.
Then I have a question, where should we set up the credentials: secret, it's not in the keycloak.rb , but it's different for different environment

**Comment by g-portugues** [comment]
> @g-portugues Thanks for your reply.
> Could I ask a quick question, where should we set up the credentials: secret, it seems not in the keycloak.rb, but it's different for each environment

Hi, @shiralwz 
Every function that uses client_id and secret has these parameters with the default value = ''. Enter these parameters in the functions or open a PR to transform the client_id and secret attributes as attr_accessor, and you can define these attributes in keycloak.rb.

**Comment by shiralwz** [comment]
Cool, thanks. I think that's a good idea. 
I will open a PR to add the missing params in keycloak.rb.

**Pull request closed without merging**
